[[redirects]]
  from = "/"
  to = "/docs/welcome/"
  status = 301

[[redirects]]
  from = "/docs/bundling"
  to = "/docs/appendix/bundling"
  status = 301

[[redirects]]
  from = "/docs/react-tutorial"
  to = "/docs/tutorials/react"
  status = 301

[[headers]]
  for = "/llms.txt"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/llms-*.txt"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/*-llms.txt"
  [headers.values]
    access-control-allow-origin = "*"
