[[redirects]]
  from = "/"
  to = "/docs/welcome/"
  status = 301

[[headers]]
  for = "/llms.txt"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/llms-*.txt"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/openrouter-llms.txt"
  [headers.values]
    access-control-allow-origin = "*"
