/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'welcome',
      label: 'Welcome'
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'react-tutorial',
        'solid-tutorial',
        'vanilla-js-tutorial',
        'chatgpt-quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'doc',
          id: 'react-tutorial',
          label: 'API Docs'
        }
      ]
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          id: 'guides/custom-queries',
          label: 'Custom Queries'
        },
        {
          type: 'doc',
          id: 'guides/working-with-files',
          label: 'Working with Files'
        },
        {
          type: 'doc',
          id: 'guides/working-with-types',
          label: 'Working with Types'
        },
        {
          type: 'doc',
          id: 'guides/fixture-data',
          label: 'Fixture Data'
        },
        {
          type: 'doc',
          id: 'guides/state-machines',
          label: 'State Machines'
        },
        {
          type: 'doc',
          id: 'guides/scaling-fireproof',
          label: 'Scaling Fireproof'
        },
        {
          type: 'doc',
          id: 'guides/time-travel',
          label: 'Time Travel'
        },
        {
          type: 'doc',
          id: 'guides/deleting-data',
          label: 'Deleting Data'
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'doc',
          id: 'architecture/core'
        },
        {
          type: 'doc',
          id: 'architecture/ledger'
        },
        {
          type: 'doc',
          id: 'architecture/gateway'
        },
        {
          type: 'doc',
          id: 'architecture/runtime'
        }
      ]
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        {
          type: 'doc',
          id: 'bundling'
        }
      ],
    }
  ],
};

module.exports = sidebars;
